languageCode = "en-us"
title = "Outbreak analytics using R"
baseURL = "https://recon-escaide-2019.netlify.com/"
theme = "../.."
googleanalytics = ""
disqusShortname = ""

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
# [params.posts]
#     foldername = "post"
#     pagesize = "6"
#     featuredpost = "true"

# [languages]
# [languages.en]
#   languageName = "English"
# [languages.es]
#   languageName = "Español"
#   title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
